CREATE TABLE IF NOT EXISTS `quotes`(
  id  INT PRIMARY KEY AUTO_INCREMENT,
  quote_name  VARCHAR(255) NOT NULL,
  created_by VARCHAR(30) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  ON UPDATE CURRENT_TIMESTAMP
);